// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaApp.DataAccess.Db.DbAccess;

namespace PizzaApp.DataAccess.Migrations
{
    [DbContext(typeof(PizzaDbAccessContext))]
    [Migration("20200916174139_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaApp.DataAccess.Core.Entities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaApp.DataAccess.Core.Entities.Pizza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("OrderID");

                    b.Property<double>("Price");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new { ID = 1, Name = "Capri", Price = 10.0, Size = 0 },
                        new { ID = 2, Name = "Peperoni", Price = 12.0, Size = 0 },
                        new { ID = 3, Name = "Funghi", Price = 14.0, Size = 0 }
                    );
                });

            modelBuilder.Entity("PizzaApp.DataAccess.Core.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PizzaApp.DataAccess.Core.Entities.Order", b =>
                {
                    b.HasOne("PizzaApp.DataAccess.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PizzaApp.DataAccess.Core.Entities.Pizza", b =>
                {
                    b.HasOne("PizzaApp.DataAccess.Core.Entities.Order")
                        .WithMany("Pizzas")
                        .HasForeignKey("OrderID");
                });
#pragma warning restore 612, 618
        }
    }
}
