using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using SEDC.PizzaApp.Domain.Enums;

namespace SEDC.PizzaApp.Domain.Models
{
    public class Order
    {
        [Key] // primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //this is generated by DB, using auto increment
        public int Id { get; set; }
        public PaymentMethod PaymentMethod { get; set; }
        public bool Delivered { get; set; }
        public string PizzaStore { get; set; }
        public List<PizzaOrder> PizzaOrders { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
    }
}
