using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace SEDC.PizzaApp.Domain.Models
{
    public class Pizza
    {
        [Key] // primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //this is generated by DB, using auto increment
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsOnPromotion { get; set; }
        public bool? HasExtras { get; set; }
        public List<PizzaOrder> PizzaOrders { get; set; }
    }
}
