using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace SEDC.PizzaApp.Domain.Models
{
    public class User
    {
        [Key] // primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //this is generated by DB, using auto increment
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string EMBG { get; set; }
        public List<Order> Orders { get; set; }
    }
}
